# This file was *autogenerated* from the file erg_graph.sage
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
from matplotlib import pyplot as plt
import numpy as np

f = open('histo.txt','r')
numx = []
numy = []
count = _sage_const_0 
for line in f:
    line = line.split()[:_sage_const_2 ]
    numx.append(int(line[_sage_const_0 ]))
    numy.append(int(line[_sage_const_1 ]))
    count += _sage_const_1 
numx.append(count)

plt.figure()
plt.bar(numx[:-_sage_const_1 ],numy,width=_sage_const_1 )
plt.xlim(min(numx), max(numx))
plt.savefig("outputs/erg_histogram.ps")

f.close()
